apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-web
  namespace: web
  labels:
    app.kubernetes.io/name: static-web
    app.kubernetes.io/instance: static-web
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: static-web
  annotations:
    description: "Service account for static web application"
automountServiceAccountToken: true
