apiVersion: v1
kind: Service
metadata:
  name: test-web-service
  namespace: test-web
  labels:
    app: test-web
spec:
  selector:
    app: test-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
