apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: static-web-project
  namespace: argocd
  labels:
    app.kubernetes.io/name: static-web-project
    app.kubernetes.io/part-of: argocd
spec:
  description: "Static Web Application Project"
  
  sourceRepos:
    - 'https://github.com/hyjk826/test_web'
    - 'https://github.com/helm/helm-charts'
    - 'https://charts.bitnami.com/bitnami'
  
  destinations:
    - namespace: 'web'
      server: 'https://kubernetes.default.svc'
    - namespace: 'staging'
      server: 'https://kubernetes.default.svc'
    - namespace: 'production'
      server: 'https://kubernetes.default.svc'
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: ReplicaSet
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: 'extensions'
      kind: Deployment
    - group: 'extensions'
      kind: ReplicaSet
    - group: 'extensions'
      kind: DaemonSet
    - group: 'extensions'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: Secret
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
  
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'extensions'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'policy'
      kind: '*'
    - group: 'rbac.authorization.k8s.io'
      kind: '*'
  
  roles:
    - name: static-web-admin
      description: "Static Web Application Administrator"
      policies:
        - p, proj:static-web-project:static-web-admin, applications, *, static-web-project/*, allow
        - p, proj:static-web-project:static-web-admin, repositories, *, *, allow
      groups:
        - static-web-admins
    
    - name: static-web-developer
      description: "Static Web Application Developer"
      policies:
        - p, proj:static-web-project:static-web-developer, applications, get, static-web-project/*, allow
        - p, proj:static-web-project:static-web-developer, applications, sync, static-web-project/*, allow
        - p, proj:static-web-project:static-web-developer, repositories, get, *, allow
      groups:
        - static-web-developers
  
  syncWindows:
    - kind: allow
      schedule: '0 0 * * *'
      duration: 24h
      applications:
        - 'static-web'
        - 'app-of-apps'
    - kind: deny
      schedule: '0 0 * * 0'
      duration: 24h
      applications:
        - 'static-web'
        - 'app-of-apps'
  
  orphanedResources:
    warn: true
