name: ArgoCD Sync

on:
  workflow_dispatch:
    inputs:
      application:
        description: 'ArgoCD Application name'
        required: true
        default: 'test-web'
      namespace:
        description: 'ArgoCD namespace'
        required: true
        default: 'argocd'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Sync ArgoCD Application
      run: |
        export KUBECONFIG=kubeconfig
        argocd app sync ${{ github.event.inputs.application }} --namespace ${{ github.event.inputs.namespace }}
        
    - name: Wait for sync
      run: |
        export KUBECONFIG=kubeconfig
        argocd app wait ${{ github.event.inputs.application }} --namespace ${{ github.event.inputs.namespace }} --timeout 300
